// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJuvy26MFfVTxjzRvRJyIkI_GQ4QRP1kU',
    appId: '1:926469953053:android:e6a9257a1a408e1f1f18f4',
    messagingSenderId: '926469953053',
    projectId: 'ielts-app-50727',
    storageBucket: 'ielts-app-50727.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBisgwYsmakLmbfKXHtmRKabVLRs1m4ooc',
    appId: '1:926469953053:ios:9d8f6d652167a4001f18f4',
    messagingSenderId: '926469953053',
    projectId: 'ielts-app-50727',
    storageBucket: 'ielts-app-50727.firebasestorage.app',
    androidClientId: '926469953053-jb7i15hqkg556q60smravq1sdp8o99vt.apps.googleusercontent.com',
    iosClientId: '926469953053-1eobsjm0odjl88rm9q9hfqni3josfsd9.apps.googleusercontent.com',
    iosBundleId: 'com.ielts.ai.app.ieltsApp',
  );

}